# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FmkFiyEe5cTdTdKuDpF9fvl0z9xahesn
"""
import os
from urllib.request import Request, urlopen
from classLibrary.ConnectClass import ConnectClass
# Table mapping response codes to messages; entries have the
# form {code: (shortmessage, longmessage)}.
connect = ConnectClass()
connect.getUrl("https://www.money101.com.tw/%E4%BF%A1%E7%94%A8%E5%8D%A1/%E7%B2%BE%E9%81%B8%E6%8E%A8%E8%96%A6?gclid=Cj0KCQjw7sz6BRDYARIsAPHzrNIsyVl9pIe0Q161BrPBO-fYKO2i1kviKYKcWnKZ2QT0xt25dsDH7IAaAj3REALw_wcB")
status_code = urlopen(connect.returnUrl()).getcode()
status_code = 300
if(status_code == 200):
    print(status_code)
else:
    os.system("python main.py")
    print(status_code)


